arb-dir: lib/l10n/arb/
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
untranslated-messages-file: untranslated_messages.json
arb-translate-api-key: AIzaSyCJeocN40_S35vMi5LoiLFKzMMowAuJYXQ


