name: pixelcraft
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  very_good_analysis: ^6.0.0
  build_runner:
  flutter_gen_runner:

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    
