name: pixelcraft
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  auto_route: ^9.1.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.6.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/images/
  - assets/icons/

flutter_gen:
  output: lib/gen/
  inputs:
  - assets/images/
  - assets/icons/

  integrations:
    flutter_svg: true
  
  colors:
    inputs:
      - assets/color/colors.xml
