name: pixelcraft
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  auto_route: ^8.1.3
  bloc: ^8.1.4
  cached_memory_image: ^1.5.0
  cupertino_icons: ^1.0.8
  dio: ^5.6.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  image_gallery_saver: ^2.0.3
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.9.0
  path: ^1.9.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  share_plus: ^10.0.2

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.6.0
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - .env

flutter_gen:
  output: lib/gen/
  inputs:
    - assets/images/
    - assets/icons/

  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/color/colors.xml
