name: pixelcraft
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  very_good_analysis: ^6.0.0

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter_gen:

  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
